Developer-Student-Clubs-UBa/hactoberfest2022

Task1/intro.json

fix issue #11 
-Added intro details in json file

feat: added Nyong Godwill as contributor

---

Task1/intro.json

feat: added rupali-codes as contributor

feat: added rupali-codes as contributor

---

Task2/socials.js

-Added socials media handles
-Resolve conflicts

feat: added Nyong Godwill socials

---

Task4/techStack.html

- Added teck stack
- Resolve conflicts

feat: added my techstack - Nyong Godwill

---

Task3/education.py

feat: added educational background of jeremie1112

---

Task4/techStack.html

feat: added my techstack - yokwejuste

---

Task3/education.py

- Added education background
- resolve conflicts

feat: added educational background of Nyong Godwill

---

Task3/education.py

I have added my  educational background since secondary education till present. Have a look on it....

feat: added educational background of iamhariom0228

---

Task4/techStack.html

I have  added my skills and technology known to me , please have a look at it!

feat: added my techstack - iamhariom0228

---

Task1/intro.json

hey !
thanks for letting me part of it !
feels nice.

task 1 contribution

---

Task1/intro.json

feat: added amanfangeria980 socials

feat: added amanfangeria980 socials

---

Task1/intro.json

Added Kshitij Verma as a contributor and fixed task1 file errors

feat: added Kshitij Verma as contributor

---

Task1/intro.json

Completed task 1 by adding myself as a Contributor

Added Vansh-Goel as the contributor

---

README.md

Draft PR is not necessary for now since contribution period has started

del: removed draft PR illustration

---

Task1/intro.json

feat: added adrzxxx as contributor

---

Task1/intro.json

Hello. Sorry for the mistake before, I added my  username as a contributor. Thank you.

added codedrian as a contributor

---

Task1/intro.json

feat: added yashg-116 as contributor

---

Task1/intro.json

feat: added Nandini-13 as contributor

---

Task3/education.py

feat: added educational background of yashg-116

---

Task1/intro.json

I created a branch that I'll use to contribute to this project for the hacktoberfest2022 edition. and I just completed task 1 by adding my details.

I just added my details

---

Task2/socials.js

I've just completed the second task by adding my social handles.

Just added my social handles

---

Task3/education.py

Just completed  task3 by adding my educational experience

Added my educational experience

---

Task4/techStack.html

I tried again after the first getting conflict. I don't really get why there is conflict

Added techstack for isaiah-0914
